#!/bin/zsh
# vim: filetype=sh
function authenticate() {
	# Must fail
	curl -i -X POST \
		-H "Content-Type: application/json" \
		-H "Accept: application/json" \
		-d '{"login": "ian", "pass": "admin"}' \
		localhost:8080/authenticate 
}
function test() {
	authenticate
}
$1
