#!/bin/zsh
# vim: filetype=sh
function authenticate() {
	curl -i -X POST \
		-H "Content-Type: application/json" \
		-H "Accept: application/json" \
		-d '{"login": "ian", "pass": "admin0"}' \
		localhost:8080/authenticate 
}

$1
